# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: John$(Date:yyyyMMdd)$(Rev:.r)

variables:
- group: TIPprojectVariableGroup

trigger:
- master

pool:
  vmImage: ubuntu-latest
stages:
- stage: BuildStage
  displayName: Build Stage
  jobs:
  - job: CreateArtifact
    displayName: 'Create Artifact'
    steps:

      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

      - script: |
          npm install
          npm run build
        displayName: 'npm install and build'

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: 'dist/angular-app1'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          replaceExistingArchive: true
        displayName: 'Archive file'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
        displayName: 'Publish'


- stage: TestStage
  displayName: Test Stage
  jobs:
  - job: TestPage
    displayName: 'Test Page'
    steps:

      - task: PowerShell@2
        name: LoginToAzureCLI
        displayName: 'Login to Azure CLI'
        inputs:
          targetType: 'inline'
          script: |        
            az login --service-principal `
            -u $(serviceprincipalid) `
            -p $(serviceprincipalpw) `
            -t ${env:TENANT}

